# [Development] shell Dockerfile
FROM node:22-slim

WORKDIR /workspace

RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy root configs for dependencies
COPY package.json pnpm-lock.yaml* nx.json tsconfig.base.json ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# App logic
EXPOSE 3000

# Start Dev Server
CMD ["pnpm", "nx", "serve", "shell", "--host", "0.0.0.0"]
